### ISSUE TITLE
The clip-retrieval ui is down and the python example does not work

### ISSUE THREAD

**Issue by alvitawa** [rom1504/clip-retrieval#179]
It appears the certificate has expired:

```
SSLError: HTTPSConnectionPool(host='knn5.laion.ai', port=443): Max retries exceeded with url: /knn-service (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
```

I get this error when running the example:

```
In [1]: from clip_retrieval.clip_client import ClipClient, Modality
   ...:
   ...: client = ClipClient(url="https://knn5.laion.ai/knn-service", indice_name
   ...: ="laion5B")

In [2]: results = client.query(text="an image of a cat")
   ...: results[0]
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
File /usr/lib/python3.10/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
```

**Comment by jaks19** [comment]
I get the same error. Any ideas on how to fix it from my end, or is it a server-side issue?

**Comment by jaks19** [comment]
This is the certificate status when I go to [https://knn5.laion.ai/knn-service](https://knn5.laion.ai/knn-service) in my browser.

![Screen Shot 2022-09-09 at 10 41 12 AM](https://user-images.githubusercontent.com/10431628/189412318-a5e9443c-22ee-430b-a463-d2bcef25016b.png)

**Comment by jaks19** [comment]
A fix I found is to not verify certificates (`verify=False` in my request to the API, in my python script.)

**Comment by kheyer** [comment]
Running into this now. The issue seems to stem from `knn5.laion.ai`. My browser gives a big `CONNECTION IS NOT PRIVATE` when I try to access the URL. Problem seems upstream of this codebase

**Comment by rom1504** [comment]
fixed now, sorry for inconvenience

**Comment by jtm732** [comment]
I am still getting timeouts with the server. It seems random.

**Comment by jaks19** [comment]
Same, happens very often and in an unpredictable way.

**Comment by rom1504** [comment]
That happens because people are sending thousands of requests to the server instead of just a few to test out.

If you want to get thousands of samples, you should get the index locally instead.

Is that your use case ?

**Comment by jtm732** [comment]
The use case in my situation is just requesting a list of images, one time, based on a query. Does client.query() send more than 1 query? I am only calling it once.

**Comment by jaks19** [comment]
That was my use case -- I reverted to doing requests one by one. 

For _downloading_ the returned URLs, massive number of async requests worked because each URL points to a unique server. 

I did the mistake of adopting the same strategy for KNN querying and just realized I am querying just one server and the large number of requests at once has not much benefit other than minimizing fractional wait times from the server. Massive downside is that there are many timeouts.

I am changing my approach to doing requests 1 by 1.

**Comment by rom1504** [comment]
Requesting one by one does not change anything.

How many requests are you doing?
If you want to do more than 1000 queries, you should probably get the index locally

**Comment by jaks19** [comment]
I am doing about a dozen but was doing them all at once.

**Comment by rom1504** [comment]
There are various things that could be done to improve performance, including implementing batching of requests.

The current API implementation is meant as a demo rather than a fully fledged dataset extraction service.

If you describe your use case in more details (maybe in a new issue), it could help shape future improvements

**Comment by rom1504** [comment]
But for sure if you get the index locally it will let you more in control of performance as you will be the only user on your own hardware

**Comment by rom1504** [comment]
I'll document that somewhere so people know better what to do depending on their use case

**Comment by jaks19** [comment]
I'll think about getting the index locally, but right now I find the size (>1TB) to be pretty big.

**Comment by rom1504** [comment]
You need a 2TB ssd yes

**Comment by jaks19** [comment]
> You need a 2TB ssd yes

Can you point me to a description or example on how to use the index locally to get the same results the API returns?

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/blob/main/notebook/simple_filter.ipynb that is pretty much what you want (at least the beginning of the notebook)

**Comment by jaks19** [comment]
Appreciate it!
